include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    missing_required_param: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Error prevention
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # Allowed for debugging during development

    # Async best practices
    unawaited_futures: true
    avoid_void_async: true

    # Null safety
    avoid_null_checks_in_equality_operators: true

    # Code quality
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_late: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true

    # Style
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Documentation (warning level for now)
    # public_member_api_docs: true  # Enable when ready

    # Flutter specific
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
